services:
  spotdl:
    image: ghcr.io/fetwar/spotify-downloader-docker
    build: .
    volumes:
      - "./config.json:/root/.spotdl/config.json"
      - "./downloads:/downloads"

  # This doesn't really work atm
  # Need to set up allowed hosts I believe
  # Docs say functionality is limited though
#  spotdl-webserver:
#    build: .
#    volumes:
#      - "./downloads:/downloads"
#    ports:
#      - "8001:80"
#    command: web --port 80 --web-use-output-dir
